### ISSUE TITLE
Does this have an option to convert idb to i64?

### ISSUE THREAD

**Issue by sciencemanx** [nlitsme/pyidbutil#2]

**Comment by nlitsme** [comment]
No, 

For several reasons:
 * There is currently no  support for writing  idb or i64 files, only reading.
 * I have only written unpackers for a few structures: the 'struct', 'enum' and bitfields.
There are many more, each have to be inspected, some are documented in the idasdk, some aren't.

So, it is certainly possible, but far from easy.
