### ISSUE TITLE
Feature request: Dump segment to raw file

### ISSUE THREAD

**Issue by vdun** [nlitsme/pyidbutil#4]
example:
`idbtool.py --dump '0xAAAA-0xBBBB' test.i64 --raw > seg.bin`

**Comment by nlitsme** [comment]
feature added.  see  https://github.com/nlitsme/pyidbutil/commit/97d5844126ae85d1a2aaff1518a48e90d594e4e4

as --dumpraw

**Comment by vdun** [comment]
Thanks.
Would be also great if you add `--dumpseg xxx` to dump segment by name instad of address range (FROM-UNTIL).
