### ISSUE TITLE
dump imports not working

### ISSUE THREAD

**Issue by shrddr** [nlitsme/pyidbutil#6]
With IDA 7.5 databases, the existing `dumpimport` code outputs nothing. I changed it a bit so it works with my files. 

```
def dumpimport(id0, node):
    startkey = id0.makekey(node+1, 'S')
    endkey = id0.makekey(node+1, 'S', 0xFFFFFFFFFFFFFFFF)
    cur = id0.btree.find('ge', startkey)
    while cur.getkey() < endkey:
        txt = id0.string(cur)
        key = cur.getkey()
        ea = id0.decodekey(key)[3]
        print("%08x: %s" % (ea, txt))
        cur.next()
```

You probably need to add some if/else handling to keep support for old format, but I don't know in which version the new format appeared.

**Comment by nlitsme** [comment]
thanks for the update.  I looked a bit deeper, and found 'S' is for named imports, and 'A' is for imports by ordinal.
I have updated pyidbtool to now output both.

And also used your correction of using 'node+1'
